// きのみタイプの最終進化形の基礎値。RaenonX ポケスリ攻略ツールのデータから作成（出典と取得方法は README.md）。
// berries はきのみおてつだい1回で拾うきのみの個数、berryBase はきのみ1個の Lv.1 でのエナジー。
// slots は食材スロット（Lv.1 / Lv.30 / Lv.60）ごとの候補 [食材, 個数]。候補は個体ごとに1つ決まり（食材配列）、
// 食材おてつだいでは3スロットから均等に1つ選ばれる。食材は所持数を埋めるのに使う。
export const MONS = {
  'butterfree': { name: 'バタフリー', berry: 'ラムのみ', berryBase: 24, time: 2500, ingP: 0.197, cap: 21, berries: 2,
    ings: { A: 'あまいミツ', B: 'あんみんトマト', C: 'ワカクサ大豆' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 4]]] },
  'raticate': { name: 'ラッタ', berry: 'キーのみ', berryBase: 28, time: 2950, ingP: 0.237, cap: 16, berries: 2,
    ings: { A: 'とくせんリンゴ', B: 'ワカクサ大豆', C: 'マメミート' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'arbok': { name: 'アーボック', berry: 'カゴのみ', berryBase: 32, time: 3400, ingP: 0.264, cap: 14, berries: 2,
    ings: { A: 'マメミート', B: 'とくせんエッグ', C: 'げきからハーブ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'raichu': { name: 'ライチュウ', berry: 'ウブのみ', berryBase: 25, time: 2200, ingP: 0.224, cap: 21, berries: 2,
    ings: { A: 'とくせんリンゴ', B: 'あったかジンジャー', C: 'とくせんエッグ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'clefable': { name: 'ピクシー', berry: 'モモンのみ', berryBase: 26, time: 2800, ingP: 0.168, cap: 24, berries: 2,
    ings: { A: 'とくせんリンゴ', B: 'あまいミツ', C: 'ワカクサ大豆' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'ninetales': { name: 'キュウコン', berry: 'ヒメリのみ', berryBase: 27, time: 2600, ingP: 0.164, cap: 23, berries: 2,
    ings: { A: 'ワカクサ大豆', B: 'ワカクサコーン', C: 'ほっこりポテト' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'primeape': { name: 'オコリザル', berry: 'クラボのみ', berryBase: 27, time: 2800, ingP: 0.2, cap: 17, berries: 2,
    ings: { A: 'マメミート', B: 'あじわいキノコ', C: 'あまいミツ' },
    slots: [[['A', 1]], [['A', 2], ['B', 1]], [['A', 4], ['B', 2], ['C', 4]]] },
  'dodrio': { name: 'ドードリオ', berry: 'シーヤのみ', berryBase: 24, time: 2300, ingP: 0.184, cap: 21, berries: 2,
    ings: { A: 'ワカクサ大豆', B: 'リラックスカカオ', C: 'マメミート' },
    slots: [[['A', 1]], [['A', 2], ['B', 1]], [['A', 4], ['B', 2], ['C', 3]]] },
  'marowak': { name: 'ガラガラ', berry: 'フィラのみ', berryBase: 29, time: 3300, ingP: 0.225, cap: 15, berries: 2,
    ings: { A: 'あったかジンジャー', B: 'リラックスカカオ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3]]] },
  'meganium': { name: 'メガニウム', berry: 'ドリのみ', berryBase: 30, time: 2800, ingP: 0.175, cap: 20, berries: 2,
    ings: { A: 'リラックスカカオ', B: 'あまいミツ', C: 'ふといながねぎ' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 5], ['C', 3]]] },
  'typhlosion': { name: 'バクフーン', berry: 'ヒメリのみ', berryBase: 27, time: 2400, ingP: 0.208, cap: 23, berries: 2,
    ings: { A: 'あったかジンジャー', B: 'げきからハーブ', C: 'ピュアなオイル' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'feraligatr': { name: 'オーダイル', berry: 'オレンのみ', berryBase: 31, time: 2800, ingP: 0.257, cap: 19, berries: 2,
    ings: { A: 'マメミート', B: 'ピュアなオイル' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3]]] },
  'xatu': { name: 'ネイティオ', berry: 'マゴのみ', berryBase: 26, time: 2500, ingP: 0.191, cap: 19, berries: 2,
    ings: { A: 'とくせんエッグ', B: 'リラックスカカオ', C: 'とくせんリンゴ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 5]]] },
  'steelix': { name: 'ハガネール', berry: 'ベリブのみ', berryBase: 33, time: 3000, ingP: 0.154, cap: 25, berries: 2,
    ings: { A: 'あんみんトマト', B: 'マメミート', C: 'ほっこりポテト' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 4], ['C', 3]]] },
  'houndoom': { name: 'ヘルガー', berry: 'ウイのみ', berryBase: 31, time: 3300, ingP: 0.203, cap: 16, berries: 2,
    ings: { A: 'げきからハーブ', B: 'あったかジンジャー', C: 'ふといながねぎ' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 4], ['C', 3]]] },
  'blaziken': { name: 'バシャーモ', berry: 'クラボのみ', berryBase: 27, time: 2600, ingP: 0.153, cap: 22, berries: 2,
    ings: { A: 'あじわいキノコ', B: 'ワカクサ大豆', C: 'ピュアなオイル' },
    slots: [[['A', 1]], [['A', 2], ['B', 4]], [['A', 4], ['B', 6], ['C', 5]]] },
  'swampert': { name: 'ラグラージ', berry: 'フィラのみ', berryBase: 29, time: 2800, ingP: 0.146, cap: 20, berries: 2,
    ings: { A: 'ワカクサコーン', B: 'モーモーミルク', C: 'あじわいキノコ' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 5], ['C', 3]]] },
  'slaking': { name: 'ケッキング', berry: 'キーのみ', berryBase: 28, time: 3600, ingP: 0.339, cap: 16, berries: 2,
    ings: { A: 'あんみんトマト', B: 'あまいミツ', C: 'とくせんリンゴ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 4], ['C', 4]]] },
  'altaria': { name: 'チルタリス', berry: 'ヤチェのみ', berryBase: 35, time: 3500, ingP: 0.258, cap: 14, berries: 2,
    ings: { A: 'とくせんエッグ', B: 'ワカクサ大豆', C: 'とくせんリンゴ' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 4], ['C', 5]]] },
  'banette': { name: 'ジュペッタ', berry: 'ブリーのみ', berryBase: 26, time: 2600, ingP: 0.179, cap: 19, berries: 2,
    ings: { A: 'ピュアなオイル', B: 'あったかジンジャー', C: 'あじわいキノコ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 4], ['C', 3]]] },
  'walrein': { name: 'トドゼルガ', berry: 'チーゴのみ', berryBase: 32, time: 3000, ingP: 0.223, cap: 18, berries: 2,
    ings: { A: 'ピュアなオイル', B: 'マメミート', C: 'あったかジンジャー' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 4], ['C', 4]]] },
  'salamence': { name: 'ボーマンダ', berry: 'ヤチェのみ', berryBase: 35, time: 2800, ingP: 0.217, cap: 22, berries: 2,
    ings: { A: 'ほっこりポテト', B: 'あったかジンジャー', C: 'マメミート' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 4], ['C', 4]]] },
  'empoleon': { name: 'エンペルト', berry: 'ベリブのみ', berryBase: 33, time: 3200, ingP: 0.168, cap: 18, berries: 2,
    ings: { A: 'とくせんエッグ', B: 'ふといながねぎ', C: 'あまいミツ' },
    slots: [[['A', 1]], [['A', 2], ['B', 1]], [['A', 4], ['B', 2], ['C', 4]]] },
  'weavile': { name: 'マニューラ', berry: 'ウイのみ', berryBase: 31, time: 2700, ingP: 0.251, cap: 21, berries: 2,
    ings: { A: 'マメミート', B: 'とくせんエッグ', C: 'ワカクサ大豆' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 4]]] },
  'musharna': { name: 'ムシャーナ', berry: 'マゴのみ', berryBase: 26, time: 2800, ingP: 0.188, cap: 24, berries: 2,
    ings: { A: 'モーモーミルク', B: 'あまいミツ', C: 'めざましコーヒー' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 2]]] },
  'tyrantrum': { name: 'ガチゴラス', berry: 'オボンのみ', berryBase: 30, time: 2800, ingP: 0.178, cap: 23, berries: 2,
    ings: { A: 'マメミート', B: 'とくせんリンゴ', C: 'ほっこりポテト' },
    slots: [[['A', 1]], [['A', 2], ['B', 3]], [['A', 4], ['B', 4], ['C', 3]]] },
  'tinkaton': { name: 'デカヌチャン', berry: 'モモンのみ', berryBase: 26, time: 2400, ingP: 0.185, cap: 20, berries: 2,
    ings: { A: 'あんみんトマト', B: 'リラックスカカオ', C: 'ほっこりポテト' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'ninetales-alola': { name: 'キュウコン(アローラのすがた)', berry: 'チーゴのみ', berryBase: 32, time: 2900, ingP: 0.232, cap: 20, berries: 2,
    ings: { A: 'ワカクサ大豆', B: 'ワカクサコーン', C: 'ほっこりポテト' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'pikachu-halloween': { name: 'ピカチュウ(ハロウィン)', berry: 'ウブのみ', berryBase: 25, time: 2500, ingP: 0.218, cap: 18, berries: 2,
    ings: { A: 'とくせんリンゴ', B: 'あったかジンジャー', C: 'とくせんエッグ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },
  'eevee-holiday': { name: 'イーブイ(ホリデー)', berry: 'キーのみ', berryBase: 28, time: 3100, ingP: 0.156, cap: 20, berries: 2,
    ings: { A: 'モーモーミルク', B: 'リラックスカカオ', C: 'マメミート' },
    slots: [[['A', 1]], [['A', 2], ['B', 1]], [['A', 4], ['B', 2], ['C', 3]]] },
  'pikachu-captain': { name: 'ピカチュウ(キャプテン)', berry: 'ウブのみ', berryBase: 25, time: 2500, ingP: 0.175, cap: 21, berries: 2,
    ings: { A: 'とくせんリンゴ', B: 'あったかジンジャー', C: 'とくせんエッグ' },
    slots: [[['A', 1]], [['A', 2], ['B', 2]], [['A', 4], ['B', 3], ['C', 3]]] },};
